apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring

metadata:
  name: my-app
  namespace: staging

spec:
  selector:
    matchLabels:
      app: my-app

  endpoints:
    - port: 8000
      path: /metrics
      interval: 30s
