apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig

metadata:
  name: my-app-frontend
  namespace: production

spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT
