apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: my-app-secrets-gke
  namespace: production

spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/python-k8s-app-demo-dt26/secrets/my-app-secret/versions/latest"
        path: "APP_SECRET"
